### ISSUE TITLE
"react-native-progressive-input/index.js"  threw an exception: TypeError: undeinfed is not an object  ( evaluating '_react2.PropTypes.string')

### ISSUE THREAD

**Issue by jpca999** [khaiql/react-native-progressive-input#13]
while updaing the expo version to ,     "expo": "^24.0.0",
  "react-native": "https://github.com/expo/react-native/archive/sdk-24.0.0.tar.gz",

I got this error message: 

How can i fix this ?

@EvanBacon 

![image](https://user-images.githubusercontent.com/1026325/34391385-14075796-eafa-11e7-991c-5395f7e57416.png)

**Comment by EvanBacon** [comment]
@jpca999 There were some syntax errors with the `TextInput`, I removed them and put in a PR #14 💙
