### ISSUE TITLE
onInputCleared doesn't seem to work

### ISSUE THREAD

**Issue by tquiroga** [khaiql/react-native-progressive-input#5]
Great job on that autocomplete @khaiql 

It's been really easy to get it running. I only have one problem with the clear Input button. The icon appear when the value is not null like it should. However when I press the icon, the icon disappear but the text stays. It seems like the function passed as the prop `onInputCleared` is never called.

I've been using bind on my context in my constructor like in your example:
```
  constructor(props) {
    super(props);
    //...
    this.onInputCleared = this.onInputCleared.bind(this);
  }
```

And then on the component I've tried that way first:
```
            <ProgressiveInput
              value={this.state.value}
              style={styles.progressiveInput}
              isLoading={this.state.isLoading}
              onChangeText={(query) => this.searchLocation(query)}
              onInputCleared={this.onInputCleared}
            />
```

Then I've tried: `onInputCleared={() => this.onInputCleared()}` or `onInputCleared={() { this.onInputCleared(); }}`. 

None of these worked. Everything else works fine.

**Comment by khaiql** [comment]
@tquiroga can you check in the example to see if the problem is still there? In case you are assigning value to the state, remember to call `this.setState({value: ''})` in `onInputCleared` handler
