### ISSUE TITLE
undefined is not an object (evaluating '_react2.PropTypes.oneOf')

### ISSUE THREAD

**Issue by Balasnest** [khaiql/react-native-progressive-input#7]
I'm currently experiencing an issue with this.
`undefined is not an object (evaluating '_react2.PropTypes.oneOf')`

I had linked this` react-native-vector-icons` package too.

**version**:
"react": "^16.0.0-rc.3",
"react-native": "^0.48.3",

How to resolve this?

**Comment by khaiql** [comment]
@Balasnest I can't help with information you provided, can you show me the code that's having issue?

**Comment by Balasnest** [comment]
@khaiql 
Facing this issue once I add this line

**import ProgressiveInput from 'react-native-progressive-input';**

`undefined is not an object (evaluating '_react2.PropTypes.oneOf')`

what would be the problem ?

**Comment by harshsrivastavaglobussoft** [comment]
@khaiql @Balasnest  Me too facing this issue when importing

`import ProgressiveInput from 'react-native-progressive-input';
`
It works perfectly with **16.0.0-alpha.12.**  But above this react version is not working. Getting this same issue http://prntscr.com/gyd6dl.

Please help me out. Badly got stuck here. It was working but after update the react version, its not working.

**Comment by khaiql** [comment]
@Balasnest @harshsrivastavaglobussoft let me work on it over the next few days.

**Comment by jpca999** [comment]
any solution for this ?

**Comment by 3axap4eHko** [comment]
`propTypes` is a separate module now `prop-types` and deprecated in module `react`

**Comment by jpca999** [comment]
We know thst but it needs to be fixed in this component.

**Comment by khaiql** [comment]
This should be fixed, kudo to @EvanBacon

**Comment by EvanBacon** [comment]
@khaiql could you merge my format update PR #10 before `npm publish` v1.1.0 <3

**Comment by danielgarciasantos** [comment]
same problem

![screenshot_1515715163](https://user-images.githubusercontent.com/16796952/34853446-e5c38986-f71a-11e7-97cc-abd979214088.png)

**Comment by EvanBacon** [comment]
@danielgarciasantos have you yarn added: "@expo/vector-icons" ?

**Comment by danielgarciasantos** [comment]
same problem

**Comment by danielgarciasantos** [comment]
I did -> yarn add @expo/vector-icons
you not have this problem?

**Comment by tokict** [comment]
His Npm version is out of date. You have old code
